**1. What is Pytorch?**

* Python based scientific computing package 
* Replacement for NumPy to use the power of GPU
* maximum flexibility and speed 

**2. Getting Started**

Tensors are similar to NumPy's ndarrays, with the additional being that 
* Tensors can also be used on a GPU to accelerate computing 

In [0]:
from __future__ import print_function
import torch

# uninitialized
x = torch.empty(5, 3)
print(x)

tensor([[3.5632e-37, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 3.6945e-02],
        [2.1347e-07, 1.6782e-07, 6.4896e-10],
        [2.6825e+23, 8.2358e-10, 1.6971e-07],
        [4.2727e-05, 5.3776e+22, 9.0681e-01]])


In [0]:
# initialized(0~1)
x = torch.rand(5, 3)
print(x)

tensor([[0.6350, 0.1110, 0.6840],
        [0.1264, 0.8355, 0.0249],
        [0.6104, 0.2295, 0.6221],
        [0.6417, 0.0576, 0.4074],
        [0.3433, 0.4123, 0.6252]])


In [0]:
# filled with zeros, dtype = long
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [0]:
# directly from data 
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [0]:
# based on an existing tensor. 
# unless new values are provided by user, will reuse properties of the input tensor 
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.0817,  1.9943, -0.7802],
        [-0.8949,  0.9439, -1.4036],
        [ 0.0651,  2.3613, -0.7846],
        [ 0.7065,  1.2808, -1.4188],
        [ 1.0613, -0.1899,  0.4224]])


In [0]:
# get the size. Since it is a tuple, it supports all tuple operations.
print(x.size())

torch.Size([5, 3])


In [0]:
# tuple operations(1)
y = torch.rand(5, 3)
print(x + y)

print(torch.add(x, y))

tensor([[ 0.6551,  2.8431,  0.1862],
        [-0.7011,  1.6420, -1.1725],
        [ 0.7323,  2.8433, -0.4262],
        [ 1.1459,  1.5516, -1.1894],
        [ 1.3686,  0.8082,  0.5569]])
tensor([[ 0.6551,  2.8431,  0.1862],
        [-0.7011,  1.6420, -1.1725],
        [ 0.7323,  2.8433, -0.4262],
        [ 1.1459,  1.5516, -1.1894],
        [ 1.3686,  0.8082,  0.5569]])


In [0]:
# torch operations(2)
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

# adds x to y
y.add_(x)
print(y)

tensor([[ 0.7367,  4.8374, -0.5940],
        [-1.5960,  2.5859, -2.5761],
        [ 0.7974,  5.2046, -1.2108],
        [ 1.8524,  2.8324, -2.6082],
        [ 2.4299,  0.6182,  0.9793]])
tensor([[ 0.7367,  4.8374, -0.5940],
        [-1.5960,  2.5859, -2.5761],
        [ 0.7974,  5.2046, -1.2108],
        [ 1.8524,  2.8324, -2.6082],
        [ 2.4299,  0.6182,  0.9793]])


In [0]:
# index like NumPy
print(y[:, 1])

tensor([4.8374, 2.5859, 5.2046, 2.8324, 0.6182])


In [0]:
# Resize with torch.view
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [0]:
# if the tensor has one element, use .item() to get the value as a Python number 
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.4944])
1.49442458152771


**3. NumPy Bridge**

Converting a Torch Tensor to a NumPy array and vice versa.

The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other. 

In [0]:
# Converting a Torch Tensor to a NumPy Array 
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [0]:
# Adding 1 to the Torch Tensor affects the numpy array 
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [0]:
# Converting NumPy ARray to Torch Tensor 
import numpy as np 

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
# a = np.add(a, 1) <-- only the NumPy value changes 
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


**4. CUDA Tensors**

Run this cell only if CUDA is available

with torch.cuda : implement the same function as CPU tensors, but they utilize GPUs for computation. 

In [0]:
if torch.cuda.is_available():
    device = torch.device("cuda")              # a CUDA device object
    y = torch.ones_like(x, device=device)      # directly create tensor on GPU
    x = x.to(device)                           # or just use strings ''.to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))