**2. Autograd: Automatic Differentiation**

The ``autograd`` package provides automatic differentiation for all operations on Tensors. 

If you set its attribute ``.requires_grad`` as True, it starts to track all operations on it. When you finish your computation you can call ``.backward()``and have all the gradients computed automatically. The gradient for this tensor will be accumulated into ``.grad`` attribute. 

In [0]:
import torch 

x = torch.ones(2, 2, requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [0]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [0]:
print(y.grad_fn)

In [0]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [0]:
# .requires_grad_(...) changes an existing Tensor's requires_grad flag in-place. 

a = torch.randn(2, 2)
a = ((a * 3)/(a - 1))
print(a.requires_grad)

a.requires_grad_(True)
print(a.requires_grad)

b = (a * a).sum()
print(b.grad_fn)

False
True


**Gradients**

Let's backprop now Because ``out`` contains a single scalar, ``out.backward()`` is equivalent to ``out.backward(torch.tensor(1)).``

In [0]:
out.backward()

In [0]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [0]:
x = torch.randn(3, requires_grad = True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([  761.4349, -1168.1293,   353.6544], grad_fn=<MulBackward0>)


In [0]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)     # gradient에는 output결과값과 동일한 shape이 들어가야 한다. 

print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [0]:
# to stop autograd from tracking history on Tensors: wrap the code block in with torch.no_grad():

print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
